apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: kalyanshiva/consumer:latest
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: MONGO_URI
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "my-cluster-kafka-bootstrap.kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
